# Generated by Django 5.0.3 on 2024-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_grade1_alter_student_grade2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matriculation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
