# Generated by Django 5.0.3 on 2024-03-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_matriculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matriculation',
            field=models.IntegerField(unique=True),
        ),
    ]
